# this setup.yml file is called from the Vagrantfile, this just means there is
# less fiddling with the Vagrantfile. There might a better way of doing things,
# to be figured out!
---
- include: folsom-stable-setup.yml
